FROM mroyon/vsftpd

# Create a config directory
USER root
RUN mkdir -p /home/vsftpd/ftpuser/blackportalftpfolder
RUN chown ftp /home/vsftpd/ftpuser/blackportalftpfolder/
RUN mkdir -p /home/vsftpd/ftpuser/blackportalftpfolder/gallary
RUN chown ftp /home/vsftpd/ftpuser/blackportalftpfolder/gallary/
RUN mkdir -p /home/vsftpd/ftpuser/blackportalftpfolder/news
RUN chown ftp /home/vsftpd/ftpuser/blackportalftpfolder/news/
RUN mkdir -p /home/vsftpd/ftpuser/blackportalftpfolder/services
RUN chown ftp /home/vsftpd/ftpuser/blackportalftpfolder/services/
RUN mkdir -p /home/vsftpd/ftpuser/blackportalftpfolder/users
RUN chown ftp /home/vsftpd/ftpuser/blackportalftpfolder/users/
RUN mkdir -p /home/vsftpd/ftpuser/blackportalftpfolder/links
RUN chown ftp /home/vsftpd/ftpuser/blackportalftpfolder/links/